const PROMPT_GROUPS = {
  apps: [
    "build a to-do list app. add a task, mark it done, remove it, and print the list after every change.",
    "make a tip calculator. take the bill and the number of people, then show what everyone owes at 15%, 18% and 20%.",
    "write a pomodoro timer. 25 minutes of work, 5 minutes of break, and after four rounds a longer 15 minute break. print each phase as it starts.",
    "build a tiny notes app. notes have a title and a body, and you can search them by any word inside.",
    "make a unit converter that turns kilometres into miles, celsius into fahrenheit and kilograms into pounds, and back again.",
    "write a budget tracker. log income and expenses with a category, then show the total spent in each category.",
    "build a habit tracker. for seven days, mark whether each habit was done and print a grid of x's and dots.",
    "make a password strength checker. score a password on length, numbers, symbols and mixed case, then say weak, okay or strong.",
    "write a random password generator. the user picks a length and whether to include symbols.",
    "build a flashcard app. show the front of a card, wait for an answer, then say right or wrong and keep score.",
    "make a shopping list that merges repeated items, so 'milk, eggs, milk' becomes '2 x milk, 1 x eggs'.",
    "write a countdown to a date. given a day, month and year, print how many days are left.",
    "build a contact book. store names and phone numbers, and let people look someone up by the start of their name.",
    "make a grade calculator. take a list of scores, then print the average, the highest, the lowest and a letter grade.",
    "write a recipe scaler. a recipe serves 4. scale every ingredient to feed any number of people.",
    "build a simple bank account with deposit, withdraw and balance. refuse a withdrawal that would go below zero.",
    "make a stopwatch with lap times. print each lap and the fastest one at the end.",
    "write an alarm clock scheduler. given a list of alarm times, print them sorted and say which one rings next after 07:30.",
    "build a reading list tracker. books are 'want to read', 'reading' or 'finished', and you can move a book between them.",
    "make a water intake tracker. log glasses through the day and print a progress bar toward 8.",
    "write a split-the-rent calculator where each person pays in proportion to the size of their room.",
    "build a mini spreadsheet. store values in cells like A1 and B2 and let one cell be the sum of others.",
    "make a calendar printer. given a month and a year, print the month laid out like a wall calendar.",
    "write a currency converter using a small table of rates you type in yourself.",
    "build a workout log. record exercise, sets and reps, then print the total reps for each exercise.",
    "make a simple invoice generator. take line items with price and quantity, add tax, and print a neat receipt.",
    "write a parking garage system. cars enter and leave, the garage has 20 spots, and it prints how many are free.",
    "build an inventory manager for a small shop. add stock, sell items, and warn when something drops below 5.",
    "make a library checkout system. books can be checked out and returned, and nobody can borrow a book that's already out.",
    "write a movie ticket booker. show a grid of seats, let someone pick a seat, and mark taken seats with an x.",
  ],
  websites: [
    "make a personal homepage. your name, a short bio, three links and a picture placeholder.",
    "build the front page of a news site: a headline, three stories with summaries, and a footer.",
    "make a product page for a pair of shoes: a name, a price, sizes to pick from and an add to cart button.",
    "build a landing page for an app that doesn't exist yet. give it a name, a one-line pitch and a signup box.",
    "make a restaurant menu page split into starters, mains and desserts, with prices lined up on the right.",
    "build a pricing page with three plans side by side. make the middle one stand out.",
    "make a photo gallery page that shows boxes in a grid which rearranges on small screens.",
    "build a login form with an email field, a password field and a 'forgot password' link. no real login, just the page.",
    "make a blog post page: title, date, author, body text, and a comments section underneath.",
    "build a simple forum front page: a list of threads with titles, reply counts and the time of the last post.",
    "make a weather page that shows the current temperature, a short description and a five-day forecast row.",
    "build a video site's watch page: a big player box, a title, a like button and a list of suggested videos on the side.",
    "make a music player page with a play button, a progress bar, a song title and a playlist below.",
    "build an 'about us' page for a made-up bakery with a team section of three people.",
    "make a 404 page that's actually funny and has a link back home.",
    "build a frequently asked questions page where each answer is hidden until you click its question.",
    "make a profile page for a social site: avatar, name, follower counts and a feed of posts.",
    "build a job board listing page with a search bar and job cards showing title, company and salary.",
    "make a portfolio page for a designer with project cards that grow slightly when you hover over them.",
    "build a stripped-down clone of a search engine homepage: a logo, one search box and two buttons.",
    "make a checkout page with a shipping address form and an order summary box.",
    "build a chat app's layout: a list of conversations on the left, messages on the right, and a text box at the bottom.",
    "make a dashboard page with four stat cards across the top and a table of recent orders below.",
    "build a wiki article page with a table of contents box and numbered sections.",
    "make an event page for a concert: date, venue, a countdown and a buy tickets button.",
  ],
  tools: [
    "write a word counter. count words, characters, sentences and the most common word in a block of text.",
    "build a text-based file tree printer. given a list of paths like 'src/app/main', print them as an indented tree.",
    "make a caesar cipher that can encrypt and decrypt with any shift.",
    "write a url parser. split a url into protocol, domain, path and query parameters.",
    "build a markdown to html converter that handles headings, bold text and bullet lists.",
    "make a csv reader. turn a few lines of comma separated text into a table with aligned columns.",
    "write a log file analyser. given lines like '12:01 ERROR disk full', count how many of each level there are.",
    "build a roman numeral converter that works both ways.",
    "make a binary, decimal and hexadecimal converter.",
    "write a duplicate finder. given a list of file names and sizes, print the ones that appear more than once.",
    "build a simple calculator that reads an expression like '3 + 4 * 2' and gets the order of operations right.",
    "make a json pretty printer for a small json string, with proper indentation.",
    "write a morse code translator, text to morse and morse back to text.",
    "build a palindrome checker that ignores spaces, punctuation and capital letters.",
    "make a timezone converter for a few cities using fixed hour offsets.",
    "write a slug maker. turn 'Hello World! My First Post' into 'hello-world-my-first-post'.",
    "build a diff tool for two short lists of lines. show which lines were added and which were removed.",
    "make an email address validator that explains why a bad address is bad.",
    "write a url shortener. give each long url a short code and look the long url back up from the code.",
    "build a colour converter between hex codes like #ff8800 and rgb values.",
    "make a text adventure map loader. read rooms and exits from a string and print where you can go from each room.",
    "write a simple spell checker that flags words not in a small dictionary and suggests the closest one.",
    "build a rate limiter. allow at most 5 requests per 10 seconds per user and reject the rest.",
    "make a command line argument parser that understands things like '--name kai --verbose'.",
    "write a tiny search index. given some documents, find which ones contain every word in a query.",
  ],
  games: [
    "make a number guessing game. the computer picks 1 to 100 and says higher or lower after each guess.",
    "build tic-tac-toe for two players on a printed grid. detect a win or a draw.",
    "make rock, paper, scissors against the computer, best of five.",
    "write hangman with a list of words. show the blanks, the wrong guesses and how many lives are left.",
    "build a text version of wordle. five letter words, six tries, and a hint for every letter.",
    "make a dice rolling simulator. roll two dice 1000 times and print how often each total came up.",
    "write blackjack against a dealer who hits until 17.",
    "build conway's game of life on a small grid and print ten generations.",
    "make a snake game board. the snake moves one step per turn and grows when it eats.",
    "write a quiz game with ten questions, a score, and a message at the end that depends on the score.",
    "build minesweeper's number logic. given a grid of mines, fill every other cell with the count of mines around it.",
    "make a memory matching game with pairs of letters hidden in a grid.",
    "write a simple battle game. a player and a monster take turns attacking with random damage until one falls.",
    "build connect four for two players with gravity, so pieces drop to the lowest empty row.",
    "make a slot machine with three reels. matching symbols pay out, and you start with 100 coins.",
    "write a maze solver that finds a path from S to E in a grid of walls and spaces.",
    "build a typing speed test. show a sentence, time how long it takes to type it, and count mistakes.",
    "make a 2048 board where sliding left merges matching tiles.",
    "write a sudoku checker that says whether a filled 9x9 grid is valid.",
    "build a choose-your-own-adventure story with at least three endings.",
  ],
  data_and_learning: [
    "make a grade book that sorts students by score and prints the top three.",
    "write a function that says whether a year is a leap year, then list every leap year from 1900 to 2100.",
    "build fizzbuzz, then change it so the words and numbers come from a list you can edit.",
    "make a temperature log that prints the hottest day, the coldest day and the average for a week.",
    "write a program that prints the first 20 prime numbers, then the first 20 fibonacci numbers.",
    "build a queue at a coffee shop. customers join, get served in order, and the program prints the wait for each.",
    "make a stack-based undo system for a text editor that supports type, delete and undo.",
    "write a bubble sort, then a selection sort, and count how many swaps each one makes on the same list.",
    "build a binary search that finds a name in a sorted list and says how many steps it took.",
    "make a family tree. store parents and children, then print everyone's grandparents.",
    "write a linked list with add, remove and print, without using the language's built-in list.",
    "build a train route finder. given stations and connections, find the route with the fewest stops.",
    "make an election counter. count votes from a list and handle a tie.",
    "write a program that turns a number like 1234 into words: 'one thousand two hundred thirty four'.",
    "build a matrix calculator that adds and multiplies two 3x3 matrices.",
    "make a leaderboard that keeps the top 10 scores in order as new scores come in.",
    "write an anagram grouper. put words like 'listen', 'silent' and 'enlist' into the same group.",
    "build a vending machine. it takes coins, sells snacks and gives back change with the fewest coins.",
    "make a traffic light that cycles green, yellow, red, and a pedestrian button that shortens green.",
    "write an elevator simulator for a 10 floor building that handles requests in a sensible order.",
  ],
  nonsense: [
    "write a program that apologises to your computer for everything you've made it run. one apology per second, ten total.",
    "build a website for a restaurant that only serves soup to ghosts. it needs opening hours, and they're all after midnight.",
    "make a banana counter. every time the user types 'banana', add one. at 12 bananas, print something unreasonable.",
    "write a horoscope generator for programming languages. python is a gemini. you decide the rest.",
    "build a dating profile page for a toaster. it enjoys long walks to the outlet.",
    "make a program that turns any sentence into pirate speak.",
    "write a weather forecast for a planet you made up. it rains spoons on tuesdays.",
    "build a to-do list that refuses to let you add more than three things because you won't do them anyway.",
    "make a calculator that is confidently wrong. it always answers 12, and explains why.",
    "write a program that names a pet rock, gives it a birthday and prints its age in rock years.",
    "build a landing page for a gym that only trains your thumbs.",
    "make an excuse generator for why your homework isn't done, built out of three random lists.",
    "write a chess board where every piece is a bishop, and print it.",
    "build a website for a museum of lost socks. every exhibit needs a sad backstory.",
    "make a program that reads a number and prints that many ducks, arranged in a triangle.",
    "write a fortune cookie that only gives fortunes about bugs in your code.",
    "build an 'online store' that sells nothing. the cart still has to add up correctly.",
    "make a program that rates a sandwich out of 10 based on its ingredients, with a strong opinion on pickles.",
    "write a clock that tells the time in bananas. one banana is 12 minutes.",
    "build a news site where every headline is about the same very small frog.",
    "make a program that argues with you. whatever you type, it disagrees politely.",
    "write a lottery for a village of 12 chimps. each chimp has a name and a lucky number.",
    "build a login page where the password is always 'banana', and the page gently mocks you for trying anything else.",
    "make a program that translates english into only vowels, then tries to translate it back.",
    "write a queue simulator for a ferris wheel operated by one very tired raccoon.",
  ],
};

const PROMPTS = Object.values(PROMPT_GROUPS).flat();
